/**
 * Generator for custom template-based context files.
 * Uses Handlebars to render user-defined templates with architectural decision data.
 * This allows teams to generate context files for any AI tool or custom format.
 */

import Handlebars from 'handlebars';
import type { ArchDecision, ArchGuardConfig, ArchCategory } from '@archguard/core';
import {
  registerHelpers,
  groupByCategory,
  groupByStatus,
  activeDecisions,
  sortByConfidence,
  getAllConstraints,
  getAllTags,
} from '../templates.js';

/** Options for custom template generation */
export interface CustomTemplateOptions {
  /** The Handlebars template string */
  template: string;
  /** Optional partial templates keyed by name */
  partials?: Record<string, string>;
  /** Additional data to pass to the template context */
  extraData?: Record<string, unknown>;
}

/**
 * Generate a custom context file from a user-defined Handlebars template.
 *
 * The template receives a rich context object with:
 * - decisions: all active decisions sorted by confidence
 * - allDecisions: all decisions including deprecated
 * - grouped: decisions grouped by category
 * - byStatus: decisions grouped by status
 * - constraints: all unique constraints
 * - tags: all unique tags
 * - config: the full ArchGuardConfig
 * - stats: summary statistics
 * - generatedAt: ISO timestamp
 *
 * All registered Handlebars helpers from templates.ts are available.
 */
export function generateCustom(
  decisions: ArchDecision[],
  config: ArchGuardConfig,
  options: CustomTemplateOptions
): string {
  const hbs = registerHelpers();

  // Register any user-provided partials
  if (options.partials) {
    for (const [name, partial] of Object.entries(options.partials)) {
      hbs.registerPartial(name, partial);
    }
  }

  const active = sortByConfidence(activeDecisions(decisions));
  const grouped = groupByCategory(active);
  const byStatus = groupByStatus(decisions);
  const constraints = getAllConstraints(active);
  const tags = getAllTags(active);

  // Build category statistics
  const categoryStats: Record<string, number> = {};
  for (const [category, catDecisions] of Object.entries(grouped)) {
    categoryStats[category] = catDecisions.length;
  }

  // Build the template context
  const context = {
    decisions: active,
    allDecisions: decisions,
    grouped,
    byStatus,
    constraints,
    tags,
    config,
    stats: {
      total: decisions.length,
      active: active.length,
      confirmed: (byStatus['confirmed'] ?? []).length,
      detected: (byStatus['detected'] ?? []).length,
      deprecated: (byStatus['deprecated'] ?? []).length,
      custom: (byStatus['custom'] ?? []).length,
      categories: categoryStats,
      avgConfidence:
        active.length > 0
          ? active.reduce((sum, d) => sum + d.confidence, 0) / active.length
          : 0,
      constraintCount: constraints.length,
      evidenceCount: active.reduce((sum, d) => sum + d.evidence.length, 0),
    },
    generatedAt: new Date().toISOString(),
    ...(options.extraData ?? {}),
  };

  const template = hbs.compile(options.template);
  return template(context);
}

/**
 * Default custom template that produces a simple summary format.
 * Useful as a starting point for users creating their own templates.
 */
export const DEFAULT_CUSTOM_TEMPLATE = `# Architecture Context
# Generated by ArchGuard (https://github.com/rjc25/ArchGuard) on {{generatedAt}}

## Summary
- Total decisions: {{stats.total}}
- Active decisions: {{stats.active}}
- Average confidence: {{stats.avgConfidence}}
- Constraints: {{stats.constraintCount}}

## Decisions
{{#each decisions}}
### {{this.title}} [{{uppercase this.status}}]
{{this.description}}

{{#ifNotEmpty this.constraints}}
Constraints:
{{bulletList this.constraints}}
{{/ifNotEmpty}}

{{/each}}

## All Constraints
{{bulletList constraints}}
`;
