/**
 * Generator for .kiro/steering.md files.
 * Produces markdown optimized for Kiro IDE's steering file format.
 * Kiro uses steering files to guide its AI assistant behavior in projects.
 */

import type { ArchDecision, ArchGuardConfig } from '@archguard/core';
import {
  groupByCategory,
  activeDecisions,
  sortByConfidence,
  getAllConstraints,
  getAllTags,
} from '../templates.js';

/**
 * Generate a .kiro/steering.md file from architectural decisions.
 *
 * Kiro's steering format uses markdown with specific section conventions:
 * - Project context and tech stack
 * - Architectural principles as steering rules
 * - Coding standards and conventions
 * - Constraints to enforce
 */
export function generateKiroSteering(
  decisions: ArchDecision[],
  config: ArchGuardConfig
): string {
  const active = sortByConfidence(activeDecisions(decisions));
  const grouped = groupByCategory(active);
  const constraints = getAllConstraints(active);
  const tags = getAllTags(active);

  const lines: string[] = [];

  // ── Header ──────────────────────────────────────────────────────
  lines.push('# Project Steering');
  lines.push('');
  lines.push(`<!-- Generated by ArchGuard (https://github.com/rjc25/ArchGuard) on ${new Date().toISOString()} -->`);
  lines.push('<!-- Do not edit generated sections. Use the user section markers for custom content. -->');
  lines.push('');

  // ── Tech Stack ──────────────────────────────────────────────────
  lines.push('## Tech Stack');
  lines.push('');
  lines.push(`- **Languages**: ${config.analysis.languages.join(', ')}`);
  lines.push(`- **Source patterns**: ${config.analysis.include.join(', ')}`);
  lines.push(`- **Excluded**: ${config.analysis.exclude.join(', ')}`);
  if (tags.length > 0) {
    lines.push(`- **Tags**: ${tags.join(', ')}`);
  }
  lines.push('');

  // ── Architectural Principles ────────────────────────────────────
  lines.push('## Architectural Principles');
  lines.push('');
  lines.push('These principles govern the architecture of this project. Follow them in all code changes.');
  lines.push('');

  const categoryLabels: Record<string, string> = {
    structural: 'Structural Architecture',
    behavioral: 'Behavioral Patterns',
    deployment: 'Deployment & Infrastructure',
    data: 'Data Architecture',
    api: 'API Design',
    testing: 'Testing Strategy',
    security: 'Security Architecture',
  };

  for (const [category, categoryDecisions] of Object.entries(grouped)) {
    const label = categoryLabels[category] ?? category;
    lines.push(`### ${label}`);
    lines.push('');

    for (const decision of categoryDecisions) {
      const confidence = Math.round(decision.confidence * 100);
      const status = decision.status.toUpperCase();
      lines.push(`**${decision.title}** — ${status} (${confidence}% confidence)`);
      lines.push('');
      lines.push(decision.description);
      lines.push('');

      if (decision.evidence.length > 0) {
        lines.push('Key references:');
        for (const ev of decision.evidence.slice(0, 3)) {
          lines.push(`- \`${ev.filePath}:${ev.lineRange[0]}\` — ${ev.explanation}`);
        }
        lines.push('');
      }
    }
  }

  // ── Coding Standards ────────────────────────────────────────────
  lines.push('## Coding Standards');
  lines.push('');
  lines.push('Adhere to these standards when writing code:');
  lines.push('');

  const structuralDecisions = grouped['structural'] ?? [];
  const apiDecisions = grouped['api'] ?? [];
  const testingDecisions = grouped['testing'] ?? [];

  if (structuralDecisions.length > 0) {
    lines.push('### File Organization');
    lines.push('');
    for (const d of structuralDecisions) {
      lines.push(`- ${d.title}: ${d.description}`);
    }
    lines.push('');
  }

  if (apiDecisions.length > 0) {
    lines.push('### API Conventions');
    lines.push('');
    for (const d of apiDecisions) {
      lines.push(`- ${d.title}: ${d.description}`);
    }
    lines.push('');
  }

  if (testingDecisions.length > 0) {
    lines.push('### Testing Conventions');
    lines.push('');
    for (const d of testingDecisions) {
      lines.push(`- ${d.title}: ${d.description}`);
    }
    lines.push('');
  }

  // ── Constraints ─────────────────────────────────────────────────
  lines.push('## Constraints');
  lines.push('');
  lines.push('These constraints are non-negotiable:');
  lines.push('');

  if (constraints.length > 0) {
    for (let i = 0; i < constraints.length; i++) {
      lines.push(`${i + 1}. ${constraints[i]}`);
    }
  } else {
    lines.push('No explicit constraints defined.');
  }
  lines.push('');

  // ── Custom Rules ────────────────────────────────────────────────
  if (config.rules.length > 0) {
    lines.push('## Custom Rules');
    lines.push('');
    for (const rule of config.rules) {
      lines.push(`- **${rule.name}** [${rule.severity}]: \`${rule.pattern}\``);
      if (rule.allowedIn) {
        lines.push(`  - Scope: allowed in ${rule.allowedIn.join(', ')}`);
      }
      if (rule.notAllowedIn) {
        lines.push(`  - Scope: not allowed in ${rule.notAllowedIn.join(', ')}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}
